version: '2'
services:
  essayage-app:
    image: essayage
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://essayage-mysql:3306/essayage?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://essayage-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://essayage-elasticsearch:9200
    ports:
      - 8383:8383
  essayage-mysql:
    extends:
      file: mysql.yml
      service: essayage-mysql
  essayage-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: essayage-elasticsearch
